
version: 2
jobs:
  build:
    docker:
      - image: base/devel
    working_directory: /data/projects
    steps:
      - checkout
      - run:
          name: prepare git
          command: pacman -Sy git cmake clang guile --noconfirm --needed
      - run:
          name: build
          command: make
      - run:
          name: package
          command: |
            cd /data/projects/out
            strip *
            tar cvf mods.tar.xz *.so
      - store_artifacts:
          path: /data/projects/out/mods.tar.xz
      - store_artifacts:
          path: /data/projects/guile.zip

workflows:
  version: 2
  build:
    jobs:
      - build